import { Assignment } from "../hooks/api/assignments";
import { Note } from "../hooks/api/notes";
import { StudentFile } from "../hooks/api/files";
import { Task } from "../hooks/api/tasks";

const now = new Date();
const yesterday = new Date(now.getTime() - 86400000).toISOString();
const tomorrow = new Date(now.getTime() + 86400000).toISOString();
const nextWeek = new Date(now.getTime() + 7 * 86400000).toISOString();

export const PLACEHOLDER_ASSIGNMENTS: Assignment[] = [
  {
    id: "p1",
    title: "Calculus Problem Set 4",
    courseId: "c1",
    course: { id: "c1", name: "Calculus I", code: "MATH101", semesterId: "s1" },
    dueDate: tomorrow,
    weight: 10,
    isSubmitted: false,
    status: "PENDING",
    createdAt: yesterday,
    updatedAt: yesterday,
  },
  {
    id: "p2",
    title: "Physics Lab Report: Optics",
    courseId: "c2",
    course: { id: "c2", name: "Physics II", code: "PHYS102", semesterId: "s1" },
    dueDate: nextWeek,
    weight: 15,
    isSubmitted: true,
    status: "SUBMITTED",
    createdAt: yesterday,
    updatedAt: yesterday,
  },
  {
    id: "p3",
    title: "World History: Essay 1",
    courseId: "c3",
    course: { id: "c3", name: "World History", code: "HIST101", semesterId: "s1" },
    dueDate: yesterday,
    weight: 20,
    isSubmitted: false,
    status: "PENDING",
    createdAt: yesterday,
    updatedAt: yesterday,
  },
  {
    id: "p4",
    title: "Data Structures Project",
    courseId: "c4",
    course: { id: "c4", name: "Comp Sci", code: "CS201", semesterId: "s1" },
    dueDate: nextWeek,
    weight: 25,
    isSubmitted: false,
    status: "PENDING",
    createdAt: yesterday,
    updatedAt: yesterday,
  },
  {
    id: "p5",
    title: "Intro to Sociology Quiz",
    courseId: "c5",
    course: { id: "c5", name: "Sociology", code: "SOC101", semesterId: "s1" },
    dueDate: nextWeek,
    weight: 5,
    isSubmitted: true,
    status: "SUBMITTED",
    createdAt: yesterday,
    updatedAt: yesterday,
  },
];

export const PLACEHOLDER_NOTES: Note[] = [
  {
    id: "n1",
    title: "Derivatives Cheat Sheet",
    content: "## Rules\n- Power Rule: nx^(n-1)\n- Product Rule: uv' + vu'\n- Quotient Rule: (uv' - vu')/v^2",
    courseId: "c1",
    course: { id: "c1", name: "Calculus I", code: "MATH101" },
    tags: ["math", "calculus", "exam"],
    createdAt: yesterday,
    updatedAt: now.toISOString(),
  },
  {
    id: "n2",
    title: "Maxwell's Equations",
    content: "1. Gauss Law\n2. Gauss Law for Magnetism\n3. Faraday's Law\n4. Ampere's Law",
    courseId: "c2",
    course: { id: "c2", name: "Physics II", code: "PHYS102" },
    tags: ["physics", "electricity"],
    createdAt: yesterday,
    updatedAt: yesterday,
  },
  {
    id: "n3",
    title: "Industrial Revolution Overview",
    content: "Key points:\n- Steam engine (James Watt)\n- Textile industry\n- Urbanization",
    courseId: "c3",
    course: { id: "c3", name: "World History", code: "HIST101" },
    tags: ["history", "notes"],
    createdAt: yesterday,
    updatedAt: yesterday,
  },
  {
    id: "n4",
    title: "Binary Search Trees",
    content: "Recursive properties:\n- Left child < Parent\n- Right child > Parent",
    courseId: "c4",
    course: { id: "c4", name: "Comp Sci", code: "CS201" },
    tags: ["cs", "algorithms"],
    createdAt: yesterday,
    updatedAt: yesterday,
  },
  {
    id: "n5",
    title: "Social Stratification",
    content: "Definitions of class, status, and power according to Weber.",
    courseId: "c5",
    course: { id: "c5", name: "Sociology", code: "SOC101" },
    tags: ["sociology", "theory"],
    createdAt: yesterday,
    updatedAt: yesterday,
  },
];

export const PLACEHOLDER_FILES: StudentFile[] = [
  {
    id: "f1",
    title: "Course Syllabus",
    originalName: "MATH101_Syllabus.pdf",
    sizeBytes: 1024 * 450,
    courseId: "c1",
    course: { id: "c1", name: "Calculus I", code: "MATH101" },
    category: "Syllabus",
    description: "Important dates and grading policy",
    createdAt: yesterday,
    updatedAt: yesterday,
    mimeType: "application/pdf",
  },
  {
    id: "f2",
    title: "Lecture 1: Intro to Waves",
    originalName: "Physics_L1.pptx",
    sizeBytes: 1024 * 1024 * 5.2,
    courseId: "c2",
    course: { id: "c2", name: "Physics II", code: "PHYS102" },
    category: "Slides",
    description: "Slide deck from Monday's lecture",
    createdAt: yesterday,
    updatedAt: yesterday,
    mimeType: "application/vnd.openxmlformats-officedocument.presentationml.presentation",
  },
  {
    id: "f3",
    title: "Lab Manual 2024",
    originalName: "Lab_Manual_v2.pdf",
    sizeBytes: 1024 * 1024 * 2.1,
    courseId: "c2",
    course: { id: "c2", name: "Physics II", code: "PHYS102" },
    category: "Lab",
    description: null,
    createdAt: yesterday,
    updatedAt: yesterday,
    mimeType: "application/pdf",
  },
  {
    id: "f4",
    title: "Review Sheet: Midterm",
    originalName: "History_Midterm_Prep.pdf",
    sizeBytes: 1024 * 850,
    courseId: "c3",
    course: { id: "c3", name: "World History", code: "HIST101" },
    category: "Exam prep",
    description: "Covers weeks 1-6",
    createdAt: yesterday,
    updatedAt: yesterday,
    mimeType: "application/pdf",
  },
  {
    id: "f5",
    title: "Final Project Guidelines",
    originalName: "CS201_Final_Project.docx",
    sizeBytes: 1024 * 120,
    courseId: "c4",
    course: { id: "c4", name: "Comp Sci", code: "CS201" },
    category: "Assignment",
    description: "Due end of semester",
    createdAt: yesterday,
    updatedAt: yesterday,
    mimeType: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
  },
];

export const PLACEHOLDER_TASKS: Task[] = [
  {
    id: "t1",
    title: "Read Chapter 4 of Sociology textbook",
    description: "Focus on the section about social mobility",
    priority: "medium",
    isCompleted: false,
    courseId: "c5",
    course: { id: "c5", name: "Sociology", code: "SOC101" },
    dueDate: tomorrow,
    createdAt: yesterday,
    updatedAt: yesterday,
  },
  {
    id: "t2",
    title: "Email Professor about extensions",
    description: "Check if I can submit the lab report on Friday",
    priority: "high",
    isCompleted: false,
    courseId: "c2",
    course: { id: "c2", name: "Physics II", code: "PHYS102" },
    dueDate: now.toISOString(),
    createdAt: yesterday,
    updatedAt: yesterday,
  },
  {
    id: "t3",
    title: "Group meeting for CS project",
    description: "Meet at the library at 5 PM",
    priority: "high",
    isCompleted: true,
    courseId: "c4",
    course: { id: "c4", name: "Comp Sci", code: "CS201" },
    dueDate: yesterday,
    createdAt: yesterday,
    updatedAt: now.toISOString(),
  },
  {
    id: "t4",
    title: "Buy a new notebook for History",
    description: "Grid paper preferred",
    priority: "low",
    isCompleted: false,
    createdAt: yesterday,
    updatedAt: yesterday,
  },
  {
    id: "t5",
    title: "Finish coding assignment 2",
    description: "Implement the linked list methods",
    priority: "medium",
    isCompleted: false,
    courseId: "c4",
    course: { id: "c4", name: "Comp Sci", code: "CS201" },
    dueDate: nextWeek,
    createdAt: yesterday,
    updatedAt: yesterday,
  },
];
